### ISSUE TITLE
GitLab CI configuration

### ISSUE THREAD

**Issue by solvemon** [jakkn/nwn-devbase#19]
Hi, and first of all, thank you a TON for your tools. I've just recently discovered this project and its already been a fantastic help in our module development!

We host our module on GitLab, and as such I was looking at how I could set up a GitLab pipeline for verifying, compiling scripts and packing the module. 

When an image is specified in a GitLab CI configuration, the whole build process is run within a container of this image. However, in order for this to work, I had to create my own version of your image, aptly named "solvemon/nwn-devbase", to clear the entry point defined in your image. Perhaps there is a better, cleaner way to achieve this?

Another thing to note, is that I was not sure in what order (or if actually needed) the resman command needs to be run? 

From the GitLab pipeline one can manually go in and download the packaged module, or set up another CI step to deploy it to the server (I have not done this yet).

In any case, it should be easy enough to play around with this config, and perhaps you can use it as part of your wiki or something. 

Here is my `.gitlab-ci.yml` file (replace the artifact path to fit your setup), I hope it can be of help to someone:

```yml
image: solvemon/nwn-devbase

stages:
    - test
    - compile
    - link
    - build
    
cache:
    key: "$CI_COMMIT_SHA"
    untracked: true
    
verify:
    stage: test
    script:
        - nwn-build verify
        
compile-scripts:
    stage: compile
    script:
        - nwn-build compile
        
link-resources:
    stage: link
    script:
        - nwn-build resman
        
pack-module:
    stage: build
    allow_failure: true
    script:
        - nwn-build pack
    artifacts:
        paths:
            - /builds/{your-group-or-username}/{your-project}/server/modules/{your-module.mod}
```

**Comment by jakkn** [comment]
Hi there! Glad to hear you find the tool useful. It's mostly just glue though - the heavy lifting is done by the underlying tools written by niv.

The ENTRYPOINT in a docker image can be overridden at runtime with the --entrypoint flag. The same goes for CMD, which is overridden by simply passing arguments. I'm not very familiar with GitLab pipelines myself, but looking up the documentation at https://docs.gitlab.com/ee/ci/docker/using_docker_images.html suggests that you can pass the entrypoint as such
```yml
image:
  name: jakkn/nwn-devbase:latest
  entrypoint: ["/bin/bash"]
```

The resman command is to support the NWNX2 plugin nwnx_resman for nwserver v1.69. Currently the command has no value to run when hosting an EE module, since NWNX:EE is still waiting for resman support. Resman provides hot reloading of module resources and is a highly valuable tool, and should it be necessary to modify the environment in a similar fashion for the EE version then I intend to make sure it works. But as it stands you don't need to run `nwn-build resman`, assuming you're running an EE module.

Let me know how the above works out and if you have any other optimizations you could use a hand with.
